services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
      PORT: 9000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped